#!/usr/bin/env bash
set -euo pipefail

IFACE=""
RULES_SRC=""
HOME_NET="10.10.10.0/24"
EXTERNAL_NET="any"

SNORT_ETC="/etc/snort"
RULES_DIR="$SNORT_ETC/rules"
CUSTOM_RULES_DIR="$RULES_DIR/custom"
MERGED_RULES="$RULES_DIR/local.rules"
CONF_FILE="$SNORT_ETC/snort.lua"
LOG_DIR="/var/log/snort"
STATE_DIR="/var/lib/snort"

LOCAL_CONF="/etc/conf.d/snort-detect"
LOCAL_START="/etc/local.d/snort.start"
LOCAL_STOP="/etc/local.d/snort.stop"
START_LOG="$LOG_DIR/startup.log"

usage() {
  cat <<EOF
Usage:
  $0 -i <iface> -r <rules_dir> [-H <home_net>] [-E <external_net>]

Options:
  -i  Interface to sniff on, e.g. eth0
  -r  Directory containing *.rules files
  -H  HOME_NET in CIDR form (default: $HOME_NET)
  -E  EXTERNAL_NET (default: $EXTERNAL_NET)

Examples:
  $0 -i eth0 -r /root/snort3-community-rules -H 10.0.0.0/24 -E any
  $0 -i eth0 -r /root/snort3-community-rules -H 10.0.0.1/32 -E any
EOF
}

while getopts "i:r:H:E:h" opt; do
  case "$opt" in
    i) IFACE="$OPTARG" ;;
    r) RULES_SRC="$OPTARG" ;;
    H) HOME_NET="$OPTARG" ;;
    E) EXTERNAL_NET="$OPTARG" ;;
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "[!] run as root" >&2
  exit 1
fi

if [[ -z "$IFACE" || -z "$RULES_SRC" ]]; then
  usage
  exit 1
fi

if [[ ! -d "$RULES_SRC" ]]; then
  echo "[!] rules dir not found: $RULES_SRC" >&2
  exit 1
fi

if ! ip link show "$IFACE" >/dev/null 2>&1; then
  echo "[!] interface not found: $IFACE" >&2
  exit 1
fi

# Normalize single IP to /32
if [[ "$HOME_NET" != */* ]]; then
  echo "[*] HOME_NET has no CIDR mask; treating it as /32"
  HOME_NET="${HOME_NET}/32"
fi

find_snort_defaults() {
  local f
  for f in \
    /usr/share/snort/snort_defaults.lua \
    /etc/snort/snort_defaults.lua \
    /usr/share/snort/lua/snort_defaults.lua
  do
    [[ -r "$f" ]] && { echo "$f"; return 0; }
  done
  return 1
}

echo "[+] updating apk indexes"
apk update

echo "[+] installing snort"
apk add --no-cache snort libpcap

SNORT_BIN="$(command -v snort || true)"
if [[ -z "$SNORT_BIN" ]]; then
  echo "[!] snort binary not found after install" >&2
  exit 1
fi

DEFAULTS_FILE="$(find_snort_defaults || true)"
if [[ -z "$DEFAULTS_FILE" ]]; then
  echo "[!] could not find snort_defaults.lua" >&2
  exit 1
fi

echo "[+] snort binary: $SNORT_BIN"
echo "[+] defaults file: $DEFAULTS_FILE"

echo "[+] creating snort user/group if needed"
addgroup -S snort 2>/dev/null || true
if ! id snort >/dev/null 2>&1; then
  adduser -S -D -H -h "$STATE_DIR" -s /sbin/nologin -G snort snort
fi

echo "[+] creating directories"
mkdir -p "$SNORT_ETC" "$RULES_DIR" "$CUSTOM_RULES_DIR" "$LOG_DIR" "$STATE_DIR" /etc/local.d /etc/conf.d
chown -R snort:snort "$LOG_DIR" "$STATE_DIR"
chmod 750 "$LOG_DIR" "$STATE_DIR"

STAMP="$(date +%F-%H%M%S)"
[[ -f "$CONF_FILE" ]] && cp -p "$CONF_FILE" "$CONF_FILE.bak.$STAMP"
[[ -f "$MERGED_RULES" ]] && cp -p "$MERGED_RULES" "$MERGED_RULES.bak.$STAMP"

echo "[+] importing rules"
: > "$MERGED_RULES"

shopt -s nullglob
RULE_FILES=( "$RULES_SRC"/*.rules )
shopt -u nullglob

if [[ ${#RULE_FILES[@]} -eq 0 ]]; then
  echo "[!] no .rules files found in $RULES_SRC" >&2
  exit 1
fi

for f in "${RULE_FILES[@]}"; do
  base="$(basename "$f")"
  cp -f "$f" "$CUSTOM_RULES_DIR/$base"
  {
    echo "# ===== BEGIN $base ====="
    cat "$f"
    echo
    echo "# ===== END $base ====="
    echo
  } >> "$MERGED_RULES"
done

chown root:snort "$MERGED_RULES"
chmod 640 "$MERGED_RULES"

echo "[+] writing Snort 3 config"
cat > "$CONF_FILE" <<EOF
-- autogenerated by install-snort3-alpine.sh

include '$DEFAULTS_FILE'

HOME_NET = '$HOME_NET'
EXTERNAL_NET = '$EXTERNAL_NET'

local custom_nets =
{
    HOME_NET       = HOME_NET,
    EXTERNAL_NET   = EXTERNAL_NET,
    DNS_SERVERS    = HOME_NET,
    SMTP_SERVERS   = HOME_NET,
    SQL_SERVERS    = HOME_NET,
    HTTP_SERVERS   = HOME_NET,
    TELNET_SERVERS = HOME_NET,
    SSH_SERVERS    = HOME_NET,
    FTP_SERVERS    = HOME_NET,
    SIP_SERVERS    = HOME_NET,
    AIM_SERVERS    = HOME_NET
}

local custom_ports = {}
if default_variables and default_variables.ports then
    custom_ports = default_variables.ports
end

ips =
{
    mode = tap,
    variables =
    {
        nets = custom_nets,
        ports = custom_ports
    },
    rules = [[
        include $MERGED_RULES
    ]]
}

alert_fast =
{
    file = true
}
EOF

chown root:snort "$CONF_FILE"
chmod 640 "$CONF_FILE"

echo "[+] testing config"
"$SNORT_BIN" -T -i "$IFACE" -c "$CONF_FILE" -l "$LOG_DIR" -k none

echo "[+] writing local.d runtime config"
cat > "$LOCAL_CONF" <<EOF
SNORT_BIN="$SNORT_BIN"
SNORT_IFACE="$IFACE"
SNORT_CONF="$CONF_FILE"
SNORT_LOG_DIR="$LOG_DIR"
SNORT_START_LOG="$START_LOG"

# detection mode only:
# no -Q
# no NFQUEUE
# no inline
SNORT_ARGS="-A alert_fast -k none"
EOF

echo "[+] writing startup script"
cat > "$LOCAL_START" <<'EOF'
#!/bin/sh
set -eu
. /etc/conf.d/snort-detect

mkdir -p "$SNORT_LOG_DIR"
: > "$SNORT_START_LOG"
chown snort:snort "$SNORT_LOG_DIR"

# Stop stale instances first
pkill -TERM -f "snort.*-c $SNORT_CONF" 2>/dev/null || true
sleep 1

"$SNORT_BIN" \
  -D \
  -u snort \
  -g snort \
  -i "$SNORT_IFACE" \
  -c "$SNORT_CONF" \
  -l "$SNORT_LOG_DIR" \
  $SNORT_ARGS \
  >>"$SNORT_START_LOG" 2>&1 || true

# Give daemon time to settle
for _ in 1 2 3 4 5; do
  if pgrep -f "snort.*-c $SNORT_CONF" >/dev/null 2>&1; then
    echo "[+] snort started"
    exit 0
  fi
  sleep 1
done

echo "[!] snort failed to start"
echo "[!] startup log: $SNORT_START_LOG"
tail -n 50 "$SNORT_START_LOG" 2>/dev/null || true
exit 1
EOF

echo "[+] writing stop script"
cat > "$LOCAL_STOP" <<'EOF'
#!/bin/sh
set -eu
. /etc/conf.d/snort-detect
pkill -TERM -f "snort.*-c $SNORT_CONF" 2>/dev/null || true
EOF

chmod +x "$LOCAL_START" "$LOCAL_STOP"

echo "[+] enabling local service at boot"
rc-update add local default >/dev/null 2>&1 || true

echo "[+] starting snort"
"$LOCAL_START"

echo
echo "[+] done"
echo "[+] config: $CONF_FILE"
echo "[+] rules:  $MERGED_RULES"
echo "[+] logs:   $LOG_DIR"
echo "[+] start log: $START_LOG"
echo "[+] check alerts with: tail -f $LOG_DIR/*"
