#! /usr/bin/env bash

R=$(which screen)

# install screen if missing.
if [ -z "$R" ]; then
    if command -v apk >/dev/null 2>&1; then
        apk add --no-cache screen
    elif command -v apt-get >/dev/null 2>&1; then
        apt-get update -y
        apt-get install -y screen
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y screen
    elif command -v yum >/dev/null 2>&1; then
        yum install -y screen
    elif command -v pacman >/dev/null 2>&1; then
        pacman -Sy --noconfirm screen
    elif command -v zypper >/dev/null 2>&1; then
        zypper --non-interactive install screen
    elif command -v xbps-install >/dev/null 2>&1; then
        xbps-install -Sy screen
    elif command -v emerge >/dev/null 2>&1; then
        emerge --ask=n app-misc/screen
    elif command -v nix-env >/dev/null 2>&1; then
        nix-env -iA nixpkgs.screen
    elif command -v pkg >/dev/null 2>&1; then
        pkg install -y screen
    elif command -v slackpkg >/dev/null 2>&1; then
        slackpkg update
        slackpkg install screen
    fi
fi

R=$(which screen)


if [ -n "$R" ]; then
    if [ -z "$LANGC" ]; then
        screen -S "$(whoami):$(tty | sed 's/\//./g')"
    fi
fi



